[image] Fix "make images-fat" build
ghaerr/elks pull request #326
Opened 2020-02-12 06:12 UTC by ghaerr

@mfld-fr:

I pulled down the latest upstream master, which only included my two latest [fat] cleanup commits, and your latest branch 'next' to 'master' merge. I noticed that the "cd image; make images-fat" was now failing, after the last executed `mcopy` inside Make.packages at the end of the do/done shell loop. It appears, for reasons I just cannot find or understand, that the exit value from the last execution of mcopy is stopping the build??! I have double-checked everything and the mcopy is not changed, and is copying, created filesystem disk image is not full.

I have looked through your commit, and can't find anything that could cause this, there's also been nothing changed on my end. Perhaps another shell is being used within make? I saw some changes to use /bin/bash and removal of CFG_SHELL in your commit, but these have nothing to do with this, my env SHELL=/bin/bash. I just don't get it.

In any case, inserting a 'true' into the loop fixes this very strange problem! I would like to ask you try running 'make images' on your system to see whether this is only occurring on OSX. If so, then I guess this PR will be needed for me, for reasons I can't explain.

Thank you!!

2020-02-12 06:14 UTC, ghaerr commented
Does the CI system run "make images" yet?

Can you explain what testing the CI system you've just implemented tests? Is it for completion of a default .config build only, or are there other cases? I'm new to CI. Thank you.

2020-02-12 08:04 UTC, mfld-fr commented
@ghaerr : please use the mailing list to discuss such topic not directly related to an issue or a PR. It becomes hard these times to follow all the threads scattered in many posts !

2020-02-12 12:09 UTC, mfld-fr requested changes

2020-02-12 12:09 UTC, mfld-fr commented on image/Make.package
> +		true; \
This is error masking. The Makefile **has** to fail whenever the `mcopy` command returns an unexpected exit code. Please investigate the reason why `mdir` returns a non-zero code and add a check for that code.

2020-02-13 03:01 UTC, ghaerr commented
Added enhanced error detection and handling when non-existent files specified in Packages file, and stop the build with a readable error message. Tested on both minix and fat image package builds, "make images" now works properly.

2020-02-13 10:21 UTC, mfld-fr approved these changes

2020-02-13 10:23 UTC, merged